version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: taskmanager-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=taskmanager
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - taskmanager-network

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskmanager-backend
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=taskmanager
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - taskmanager-network

  frontend:
    build:
      context: ./frontend  # изменили контекст на папку frontend
      dockerfile: Dockerfile  # используем стандартное имя
    container_name: taskmanager-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1
    restart: unless-stopped
    networks:
      - taskmanager-network

volumes:
  mongodb_data:

networks:
  taskmanager-network:
    driver: bridge